close all; clear; clc;

% Parameters
I = 1; % Current A
mu = (4*pi)*1e-7; % Permeability of space
L = 5;
n = 10;

% Meshgrid of the 3D space
[X, Y, Z] = meshgrid(linspace(-5, 5, n), linspace(-5, 5, n), linspace(-L, L, n));

% Calculations of the Magnetic field generated by the current
rho = sqrt(X.^2 + Y.^2);

u1 = Z + L/2;
u2 = Z - L/2;

B = ((mu.*I)./(4.*pi.*rho)) .* ((u1./sqrt(rho.^2 + u1.^2)) - (u2./sqrt(rho.^2 + u2.^2)));

B(B == 0) = 0;

% X-Y components of the field
Bx = -B.*(Y./rho);
By = B.*(X./rho);

Bz = zeros(size(B)); % There is no Z component of the magnetic field, since it is purely tangential


% Visualization of the magnetic field
figure; hold on;

hQ = quiver3(X, Y, Z, Bx, By, Bz);
hQ.LineWidth = 2;
set(hQ, 'UData', Bx, 'VData', By, 'WData', Bz);

% Visualization of the field lines
theta = linspace(0, pi/4, 1);
r0 = 1;
z0_levels = linspace(-L/2, L/2, 10);

[sx, sy, sz] = deal([]);
for z0 = z0_levels
    sx = [sx; r0*cos(theta)'];
    sy = [sy; r0*sin(theta)'];
    sz = [sz; z0*ones(size(theta'))];
end

verts = stream3(X, Y, Z, Bx, By, Bz, sx, sy, sz, [0.05, 2000]);

streamline(verts, 'LineWidth', 1.5);

z_wire = linspace(-L/2, +L/2, 100);
plot3( zeros(size(z_wire)), zeros(size(z_wire)), z_wire, 'r', 'LineWidth', 5);

xlabel('X-axis');
ylabel('Y-axis');
zlabel('Z-axis');
title('Magnetic Field Visualization with a rod');
grid on;
view(3)
axis equal;
view(3);
hold off;